name: nocks

services:
  nock1:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock2:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock3:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock4:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock5:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock6:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock7:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock8:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
  nock9:
    image: ghcr.io/wowdogemonster/nockchain-miner:latest
